"""msg

Revision ID: 44f5832e1163
Revises: 8e9d6a8821fd
Create Date: 2022-01-02 03:00:25.980478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f5832e1163'
down_revision = '8e9d6a8821fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom', sa.Column('color_default', sa.String(), nullable=True))
    op.add_column('custom', sa.Column('length', sa.String(), nullable=True))
    op.drop_constraint('custom_guest_id_key', 'custom', type_='unique')
    op.drop_column('custom', 'color_')
    op.drop_column('custom', 'text_note')
    op.drop_column('custom', 'guest_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom', sa.Column('guest_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('custom', sa.Column('text_note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('custom', sa.Column('color_', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('custom_guest_id_key', 'custom', ['guest_id'])
    op.drop_column('custom', 'length')
    op.drop_column('custom', 'color_default')
    # ### end Alembic commands ###
